version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Database25!
      POSTGRES_DB: flowup
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    depends_on:
      - db
    environment:
      PORT: 3000
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PASSWORD: Database25!
      DATABASE_NAME: flowup
      JWT_SECRET: supersecret_change_me
      JWT_EXPIRES_IN: 3600s
    ports:
      - "3000:3000"

volumes:
  pgdata:
